# Smart-Inventory-Builder & iSystemDevelopment Projects - License Agreement

**Proprietary Software – All Rights Reserved**

---

## 1. Grant of License

All systems, code, documentation, and assets herein are the proprietary work of **iSystem Development**.  
They are licensed exclusively to specified clients (e.g., GSL Power Ltd) for internal business use, per contract terms.

- No redistribution, public disclosure, or third-party publication is permitted without written approval from iSystem Development.
- AI-powered processes, orchestrations, and collaboration patterns are covered by this license.

---

## 2. Restrictions

- **No Commercial Redistribution:**  
  No resale, sublicense, or publication in any form.
- **No Reverse Engineering:**  
  Systems, code, code generators, or AI workflows may not be reverse engineered.
- **Confidentiality:**  
  Credentials, customer data, and business secrets must remain confidential at all times.

---

## 3. Dual-Repo/Portfolio Architecture

- Public repositories include only sanitized code and knowledge — no production secrets, business data, or proprietary integrations.
- Private repositories are for operational systems; production deployments handled exclusively under license agreements.

---

## 4. Support, Warranty & Intellectual Property

- AS-IS, unless otherwise stated via support contract.
- iSystem Development retains intellectual property rights.
- Licensees retain business data generated by usage.

---

## 5. Contact

**Developer:** iSystem Development  
**Lead:** Arkadiusz (Dr-Diodac)  
**Email:** info@isystem.app  
**License Date:** November 2024

---

## 6. Acceptance

Use of any iSystemDevelopment assets constitutes acceptance of these terms.

---

**Copyright © 2024–2025 iSystem Development, AI-Human Dreamteam**
All rights reserved.
