name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          if [ -f package.json ] && npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script defined, skipping."
          fi

      - name: Test
        run: |
          if [ -f package.json ] && npm run | grep -q "test"; then
            npm test -- --ci || npm test || echo "Tests failed"; exit 1
          else
            echo "No test script defined, skipping."
          fi

      - name: Build
        run: |
          if [ -f package.json ] && npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script defined, skipping."
          fi
