name: Secret Scanning

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 4 * * *"  # Daily at 04:00 UTC
  workflow_dispatch:

jobs:
  gitleaks:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  trufflehog:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  pattern-check:
    name: Pattern Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for common secret patterns
        run: |
          echo "Scanning for common credential patterns..."
          
          # Define patterns to search for
          PATTERNS=(
            "AKIA[0-9A-Z]{16}"                           # AWS Access Key
            "(?i)(aws_secret_access_key|aws_session_token)\s*[:=]\s*['\"][A-Za-z0-9/+=]{40}['\"]"  # AWS Secret
            "-----BEGIN.*(RSA|OPENSSH|DSA|EC|PGP).*PRIVATE KEY"  # Private Keys
            "(?i)(api[_-]?key|apikey|access[_-]?token)\s*[:=]\s*['\"][a-zA-Z0-9_\-]{20,}['\"]"  # API Keys
            "ghp_[a-zA-Z0-9]{36}"                        # GitHub Personal Access Token
            "gho_[a-zA-Z0-9]{36}"                        # GitHub OAuth Token
            "ghs_[a-zA-Z0-9]{36}"                        # GitHub Server-to-Server Token
            "ghr_[a-zA-Z0-9]{36}"                        # GitHub Refresh Token
            "sk-[a-zA-Z0-9]{20,50}"                      # OpenAI/Stripe API Key
            "(?i)(password|passwd|pwd)\s*[:=]\s*['\"][^'\"]{8,}['\"]"  # Passwords
            "mongodb(\+srv)?://[^:]+:[^@]+@"             # MongoDB connection string with password
            "postgres://[^:]+:[^@]+@"                    # PostgreSQL connection string with password
            "mysql://[^:]+:[^@]+@"                       # MySQL connection string with password
          )

          # Files to exclude from scanning
          EXCLUDE_DIRS="(.git|node_modules|dist|build|.vscode|.idea)"
          EXCLUDE_FILES="(package-lock.json|yarn.lock|*.min.js|CREDENTIAL_SECURITY.md|secret-scanning.yml)"

          FOUND=0
          
          for pattern in "${PATTERNS[@]}"; do
            echo "Checking pattern: $pattern"
            
            # Use grep with perl regex, excluding certain paths
            MATCHES=$(grep -rIPn "$pattern" . \
              --exclude-dir="$EXCLUDE_DIRS" \
              --exclude="$EXCLUDE_FILES" \
              2>/dev/null || true)
            
            if [ -n "$MATCHES" ]; then
              echo "::error::Potential secret found matching pattern: $pattern"
              echo "$MATCHES"
              FOUND=1
            fi
          done

          # Check for [REDACTED_*] placeholders that might indicate sanitized content
          REDACTED=$(grep -rn "\[REDACTED_" . \
            --exclude-dir="$EXCLUDE_DIRS" \
            --exclude="$EXCLUDE_FILES" \
            2>/dev/null || true)
          
          if [ -n "$REDACTED" ]; then
            echo "::warning::Found sanitized credentials (REDACTED placeholders):"
            echo "$REDACTED"
            echo "These should be replaced with proper documentation or environment variable references."
          fi

          if [ $FOUND -eq 1 ]; then
            echo "::error::Secret patterns detected! Please review and remove credentials."
            exit 1
          else
            echo "✅ No credential patterns detected."
          fi

  file-check:
    name: Check for Sensitive Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for sensitive files
        run: |
          echo "Checking for sensitive files..."
          
          # Find sensitive files
          SENSITIVE_FILES=$(find . -type f \( \
            -name ".env" -o \
            -name ".env.*" -o \
            -name "*.pem" -o \
            -name "*.key" -o \
            -name "*.crt" -o \
            -name "*.p12" -o \
            -name "*.pfx" -o \
            -name "*.jks" -o \
            -name "*.keystore" \
          \) ! -path "./.git/*" ! -name ".env.example" ! -name "*.pub.key" || true)

          if [ -n "$SENSITIVE_FILES" ]; then
            echo "::error::Sensitive files found that should not be committed:"
            echo "$SENSITIVE_FILES"
            exit 1
          else
            echo "✅ No sensitive files detected."
          fi
