name: Secret Scanning

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main", "develop"]
  schedule:
    - cron: "0 2 * * *"  # Daily at 02:00 UTC
  workflow_dispatch:

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better detection

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  custom-patterns:
    name: Custom Pattern Detection
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan for hardcoded credentials
        run: |
          echo "Scanning for hardcoded credential patterns..."
          
          # Define patterns to search for
          PATTERNS=(
            "password\s*[:=]\s*[\"'][^\"']{8,}[\"']"
            "api_key\s*[:=]\s*[\"'][^\"']{8,}[\"']"
            "secret\s*[:=]\s*[\"'][^\"']{8,}[\"']"
            "token\s*[:=]\s*[\"'][^\"']{8,}[\"']"
            "private_key\s*[:=]"
            "aws_access_key_id\s*[:=]"
            "aws_secret_access_key\s*[:=]"
            "AKIA[0-9A-Z]{16}"  # AWS Access Key pattern
            "-----BEGIN (RSA |DSA )?PRIVATE KEY-----"
          )
          
          FOUND=false
          
          for pattern in "${PATTERNS[@]}"; do
            echo "Checking pattern: $pattern"
            MATCHES=$(grep -rn -E "$pattern" \
              --include="*.js" --include="*.ts" --include="*.py" \
              --include="*.java" --include="*.go" --include="*.rb" \
              --include="*.php" --include="*.yml" --include="*.yaml" \
              --include="*.json" --include="*.md" --include="*.txt" \
              --include="*.sh" --include="*.env" \
              --exclude-dir=".git" --exclude-dir="node_modules" \
              . | grep -v "REDACTED" | grep -v "YOUR-" | grep -v "example" | grep -v "\${{" | grep -v "secrets\." || true)
            
            if [ -n "$MATCHES" ]; then
              echo "::error::Potential hardcoded credentials found:"
              echo "$MATCHES"
              FOUND=true
            fi
          done
          
          if [ "$FOUND" = true ]; then
            echo "::error::Hardcoded credentials detected. Please use environment variables or secrets management."
            exit 1
          fi
          
          echo "✓ No hardcoded credentials detected"

      - name: Check for secret files
        run: |
          echo "Checking for secret files..."
          
          SECRET_FILES=$(find . -type f \( \
            -name "*.pem" -o \
            -name "*.key" -o \
            -name "*.crt" -o \
            -name "*.p12" -o \
            -name "*.pfx" -o \
            -name ".env" -o \
            -name ".env.*" -o \
            -name "*credentials*" -o \
            -name "*secret*" -o \
            -name "id_rsa" -o \
            -name "id_dsa" -o \
            -name "id_ecdsa" -o \
            -name "id_ed25519" \
          \) ! -name ".env.example" ! -name "*.md" \
            -not -path "./.git/*" | sed 's|^\./||' || true)
          
          if [ -n "$SECRET_FILES" ]; then
            echo "::error::Secret files found in repository:"
            echo "$SECRET_FILES"
            echo "These files should not be committed. Add them to .gitignore."
            exit 1
          fi
          
          echo "✓ No secret files found"
