name: Secret Scanning

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Scan for hardcoded credentials
        run: |
          echo "Scanning for potential hardcoded credentials..."
          
          # Define patterns for common credential types (scanned in all files)
          PATTERNS=(
            'AKIA[0-9A-Z]{16}'                           # AWS Access Key
            'sk_live_[0-9a-zA-Z]{24,}'                   # Stripe API Key
            'pk_live_[0-9a-zA-Z]{24,}'                   # Stripe Publishable Key
            'ghp_[0-9a-zA-Z]{36}'                        # GitHub Personal Access Token
            'gho_[0-9a-zA-Z]{36}'                        # GitHub OAuth Token
            'github_pat_[0-9a-zA-Z_]{82}'                # GitHub Fine-grained PAT
            'glpat-[0-9a-zA-Z_-]{20}'                    # GitLab PAT
            'ya29\.[0-9A-Za-z_-]+'                       # Google OAuth Token
            'AIza[0-9A-Za-z_-]{35}'                      # Google API Key
            '[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com' # Google OAuth Client ID
            'xox[pboa]-[0-9]{10,12}-[0-9]{10,12}-[0-9a-zA-Z]{24,}' # Slack Token
            'https://hooks\.slack\.com/services/T[a-zA-Z0-9_]+/B[a-zA-Z0-9_]+/[a-zA-Z0-9_]+' # Slack Webhook
            'postgres://[a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+@'  # PostgreSQL Connection String
            'mongodb(\+srv)?://[a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+@' # MongoDB Connection String
            'mysql://[a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+@'     # MySQL Connection String
            'redis://[a-zA-Z0-9_-]*:[a-zA-Z0-9_-]+@'     # Redis Connection String
            '-----BEGIN (RSA |DSA |EC |OPENSSH )?PRIVATE KEY-----' # Private Keys
          )
          
          # Password pattern - excluded from markdown files to avoid false positives in documentation
          PASSWORD_PATTERN='(password|passwd|pwd)["\s]*[:=]["\s]*[^\s]{8,}'
          
          FOUND=false
          
          # Scan files excluding git directory and common binary/vendor paths
          for pattern in "${PATTERNS[@]}"; do
            echo "Checking pattern: ${pattern:0:30}..."
            MATCHES=$(grep -rIE "$pattern" . \
              --exclude-dir=.git \
              --exclude-dir=node_modules \
              --exclude-dir=vendor \
              --exclude-dir=dist \
              --exclude-dir=build \
              --exclude="*.log" \
              --exclude="*.min.js" \
              --exclude="package-lock.json" \
              2>/dev/null || true)
            
            if [ -n "$MATCHES" ]; then
              echo "::warning::Potential credential pattern found: ${pattern:0:30}"
              echo "$MATCHES"
              FOUND=true
            fi
          done
          
          # Check password pattern separately, excluding markdown files
          echo "Checking pattern: ${PASSWORD_PATTERN:0:30}..."
          MATCHES=$(grep -rIE "$PASSWORD_PATTERN" . \
            --exclude-dir=.git \
            --exclude-dir=node_modules \
            --exclude-dir=vendor \
            --exclude-dir=dist \
            --exclude-dir=build \
            --exclude="*.log" \
            --exclude="*.min.js" \
            --exclude="*.md" \
            --exclude="package-lock.json" \
            2>/dev/null || true)
          
          if [ -n "$MATCHES" ]; then
            echo "::warning::Potential credential pattern found: ${PASSWORD_PATTERN:0:30}"
            echo "$MATCHES"
            FOUND=true
          fi
          
          if [ "$FOUND" = true ]; then
            echo "::error::Potential credentials detected in repository. Please review and remove them."
            exit 1
          fi
          
          echo "✅ No hardcoded credentials detected."
      
      - name: Check for sensitive file types
        run: |
          echo "Checking for sensitive file types..."
          
          SENSITIVE_FILES=$(find . -type f \( \
            -name ".env" -o \
            -name ".env.*" -o \
            -name "*.pem" -o \
            -name "*.key" -o \
            -name "*.crt" -o \
            -name "*.p12" -o \
            -name "*.pfx" -o \
            -name "*.keystore" -o \
            -name "*.jks" -o \
            -name "id_rsa" -o \
            -name "id_dsa" -o \
            -name "id_ecdsa" -o \
            -name "id_ed25519" -o \
            -name "*.ppk" -o \
            -name "credentials.json" -o \
            -name "credentials.yml" -o \
            -name "credentials.yaml" -o \
            -name "secrets.json" -o \
            -name "secrets.yml" -o \
            -name "secrets.yaml" \
          \) 2>/dev/null | grep -v ".git/" || true)
          
          if [ -n "$SENSITIVE_FILES" ]; then
            echo "::error::Sensitive files detected that should not be committed:"
            echo "$SENSITIVE_FILES"
            exit 1
          fi
          
          echo "✅ No sensitive files detected."
      
      - name: Verify .gitignore exists
        run: |
          if [ ! -f .gitignore ]; then
            echo "::warning::.gitignore file not found. Consider adding one to prevent accidental commits."
          else
            echo "✅ .gitignore file exists."
            
            # Check if .gitignore contains common credential patterns
            IMPORTANT_PATTERNS=(".env" "*.pem" "*.key" "credentials")
            MISSING=()
            
            for pattern in "${IMPORTANT_PATTERNS[@]}"; do
              if ! grep -q "$pattern" .gitignore; then
                MISSING+=("$pattern")
              fi
            done
            
            if [ ${#MISSING[@]} -gt 0 ]; then
              echo "::warning::.gitignore is missing important patterns: ${MISSING[*]}"
            else
              echo "✅ .gitignore contains important credential patterns."
            fi
          fi
