name: Secret Detection Alert

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  detect-and-alert:
    name: Detect Secrets and Create Alert
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run secret detection
        id: detect
        continue-on-error: true
        run: |
          echo "Running secret detection..."
          
          # Create results directory
          mkdir -p /tmp/secret-scan-results
          
          # Initialize result tracking
          SECRETS_FOUND=0
          
          # Check for common secret patterns
          echo "Scanning for credential patterns..."
          
          PATTERNS=(
            "AKIA[0-9A-Z]{16}"  # AWS Access Key
            "-----BEGIN (RSA |DSA |EC )?PRIVATE KEY-----"  # Private keys
            "password\s*[:=]\s*[\"'][^\"']{8,}[\"']"
            "api_key\s*[:=]\s*[\"'][^\"']{20,}[\"']"
            "token\s*[:=]\s*[\"'][^\"']{20,}[\"']"
          )
          
          for pattern in "${PATTERNS[@]}"; do
            MATCHES=$(grep -rn -E "$pattern" \
              --include="*.js" --include="*.ts" --include="*.py" \
              --include="*.java" --include="*.go" --include="*.yml" \
              --include="*.yaml" --include="*.json" --include="*.md" \
              --include="*.sh" --include="*.txt" \
              --exclude-dir=".git" --exclude-dir="node_modules" \
              . | grep -v "REDACTED" | grep -v "YOUR-" | grep -v "example" | grep -v "\${{" | grep -v "secrets\." || true)
            
            if [ -n "$MATCHES" ]; then
              echo "$MATCHES" >> /tmp/secret-scan-results/findings.txt
              SECRETS_FOUND=$((SECRETS_FOUND + 1))
            fi
          done
          
          # Check for secret files
          echo "Checking for secret files..."
          
          SECRET_FILES=$(find . -type f \( \
            -name "*.pem" -o -name "*.key" -o -name "*.crt" -o \
            -name ".env" -o -name "id_rsa" -o -name "id_dsa" \
          \) ! -name ".env.example" -not -path "./.git/*" || true)
          
          if [ -n "$SECRET_FILES" ]; then
            echo "$SECRET_FILES" >> /tmp/secret-scan-results/secret-files.txt
            SECRETS_FOUND=$((SECRETS_FOUND + 1))
          fi
          
          echo "secrets_found=$SECRETS_FOUND" >> $GITHUB_OUTPUT
          
          if [ $SECRETS_FOUND -gt 0 ]; then
            echo "found=true" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Create security alert issue
        if: steps.detect.outputs.found == 'true' && github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const findings = fs.existsSync('/tmp/secret-scan-results/findings.txt') 
              ? fs.readFileSync('/tmp/secret-scan-results/findings.txt', 'utf8') 
              : 'No pattern findings';
            const secretFiles = fs.existsSync('/tmp/secret-scan-results/secret-files.txt')
              ? fs.readFileSync('/tmp/secret-scan-results/secret-files.txt', 'utf8')
              : 'No secret files found';
            
            const issueBody = `## 🚨 Secret Detection Alert
            
            **Scan Date:** ${new Date().toISOString()}
            **Branch:** ${context.ref}
            **Commit:** ${context.sha}
            
            ### ⚠️ Potential Secrets Detected
            
            Our automated secret scanning has detected potential credentials or sensitive data in the repository.
            
            ### Findings
            
            #### Pattern Matches
            \`\`\`
            ${findings}
            \`\`\`
            
            #### Secret Files
            \`\`\`
            ${secretFiles}
            \`\`\`
            
            ### 🔴 URGENT ACTION REQUIRED
            
            1. **Verify** if these are actual secrets or false positives
            2. **Revoke** any exposed credentials immediately
            3. **Remove** secrets from the repository
            4. **Rotate** compromised credentials
            5. **Update** .gitignore to prevent future commits
            
            ### Next Steps
            
            - Review [SECURITY.md](../blob/main/SECURITY.md) for credential management
            - Follow [SECURITY_CHECKLIST.md](../blob/main/SECURITY_CHECKLIST.md)
            - Use environment variables or GitHub Secrets
            - Enable pre-commit hooks to prevent future incidents
            
            ---
            *This alert was automatically generated by Secret Detection workflow.*
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 URGENT: Potential Secrets Detected in ${context.ref}`,
              body: issueBody,
              labels: ['security', 'urgent', 'credentials']
            });

      - name: Fail workflow if secrets found
        if: steps.detect.outputs.found == 'true'
        run: |
          echo "::error::Secrets detected in repository. Please review and remove them."
          exit 1
