name: Security Scan

on:
  schedule:
    - cron: "0 3 * * *"  # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  node-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json found, skipping Node security scan."
          fi

      - name: Run npm audit
        run: |
          if [ -f package.json ]; then
            npm audit --audit-level=high || true
          fi
